{% set name = "fv3grid" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fv3grid-{{ version }}.tar.gz
  sha256: e4edeabcf2371a84b5905e99243beb4be3547b360353e64b12de35fc37bd0d4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - netcdf4

test:
  imports:
    - fv3grid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/noaa-oar-arl/fv3grid
  summary: FV3 Grid Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bbakernoaa
    - zmoon
